### ISSUE TITLE
Define the interactions of docker-compose.yml and benchflow-benchmark.yml

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#189]
_From @VincenzoFerme on February 8, 2016 21:21_

@simonedavico define the interactions of docker-compose.yml and benchflow-compose.yml files, the generated values and the variables we expose to docker-compose.yml

Example of file:

``` yml
camunda:
  image: 'camunda/camunda-bpm-platform:tomcat-7.4.0'
  # Generated
  # container_name: camunda_TRIAL_ID
  environment:
    - DB_DRIVER=com.mysql.jdbc.Driver
    - DB_PASSWORD=camunda
    # the IP Must be the local IP
    - 'DB_URL=jdbc:mysql://${BENCHFLOW_COMPOSE_DB_IP}:3306/process-engine'
    - DB_USERNAME=camunda
    - 'JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom'
    # Generated
    # - "constraint:node==lisa1"
  net: host
  ports:
    - '8080:8080'

db:
  image: 'mysql:latest'
  # Generated
  # container_name: db_TRIAL_ID
  environment:
    - MYSQL_DATABASE=process-engine
    - MYSQL_PASSWORD=camunda
    - MYSQL_ROOT_PASSWORD=camunda
    - MYSQL_USER=camunda
    # Generated
    # - "constraint:node==bull"
  net: host
  ports:
    - '3306:3306'
```

_Copied from original issue: benchflow/drivers-maker#17_
