### ISSUE TITLE
Define the mapping between the benchflow-configuration file and the Faban configuration

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#191]
_From @VincenzoFerme on December 29, 2015 14:28_

We always need to keep the mappings between our configuration file and the faban configuration files.

We agreed that we are going to map the configuration by first generating a run.yml corresponding to the run.xml command, so that then the /convert method will simply convert the run.yml to run.xml

_Copied from original issue: benchflow/drivers-maker#8_

**Comment by VincenzoFerme** [comment]
@simonedavico we need to start with this, now that we are starting to change it.

Information that need to be present in the `run.xml`: sut endpoint, benchflow services (compose, [mapped services differentiating start and stop endpoints]), trial_ID

Some more details follows:

Sut endpoint, benchflow/compose and trial_ID can be specified as follows:

``` yml
sut-configuration:
   endpoint: sut_endpoint

benchlow-run-configuration:
   trial_id: current_trial_id

benchflow-services-configuration:
   compose: http://compose:8080
```

---

In the `run.xml` file we also need the list of collectors to be contacted by the driver at `start` and `stop` time (see https://github.com/benchflow/collectors/issues/38#issuecomment-184417147). The port of the collector is determined at runtime, so we need to resolve it through [benchflow/compose](https://github.com/benchflow/compose). For doing that we need the list of the services name as they are defined in the `docker-compose.yml` file generated for the deployment. Since we also need to know the endpoint of these services to be called at `start` and `stop` time, a possible structure of this information in yml (then directly translated to xml) could be:

``` yaml
collectors:
    stats:
         start: /start
         stop: /stop
    mysql:
         stop: /data
```

---
