### ISSUE TITLE
Support docker compose`v3` for specifying resources

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#380]
support soft and hard limits, see https://codefresh.io/blog/deploy-docker-compose-v3-swarm-mode-cluster/

```
resources:
  limits: # hard limit - docker does not allow to allocate more
    memory: 5M
    cpu: 25% 
  reservations: # soft limit - docker makes best effort to return to it
    memory: 5M
    cpu: 25%   
```

Needs (currently) to be converted to `v2` because it is used in `driver-maker`:
- `limits: memory => mem_limit`
- `reservations: memory => mem_reservation`

For cpu we we wait until BenchFlow supports `v3` because it is difficult to map.
