### ISSUE TITLE
Add SUT service configuration section in DSL

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#398]
Add service specific configuration to support overriding of docker-compose (but this is overridden by the goal configuration exploration):

```
sut:
# OPTIONAL
  # service specific configuration
  { String : <name of service>}:
    # optional, can be specified in docker compose file by user
    resources: # specified as YAML block collection
      - memory: { Number : <memory size in MB> }
      - cores: { Number : <number of cores> }
      ...
    environment:
      ...
```

Resources specification needs to be updated according to https://github.com/benchflow/benchflow/issues/380

This also includes checking this section when generating the experiment bundles
