### ISSUE TITLE
Enable to specify the workload_execution in the goal specification, when that goal is a load

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/benchflow#422]

**Comment by jeppe-style** [comment]
@VincenzoFerme I don't get this. If the goal is `load` there is only one experiment.

**Comment by VincenzoFerme** [comment]
We discussed to have the possibility to specify the following:

```YAML
configuration:
  goal:
    type: "load"
    observation: ...
    users: { Number : <total number of users to be simulated> }
    workload_execution:
        ramp_up: { String : <time in seconds + "s" (seconds)> }
        steady_state: { String : <time in seconds + "s" (seconds)> }
        ramp_down: { String : <time in seconds + "s" (seconds)> }
  termination_criteria: ...
```
