### ISSUE TITLE
Defaults for `data_collection.client_side.faban` if missing

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#437]
We should provide defaults for `data_collection.client_side.faban` if the user did not specify them: `max_run_time` and `interval`

```
data_collection:
  client_side:
    faban:
      max_run_time: { String : <max runtime on Faban for a single trial + "h" (hour)>} # default 6h
      interval: { String : <time + "s" (seconds)> } # default 1s
```

We should provide the default as a case class in `FabanConfiguration`. Needs to consider that one of the two values might be specified, so probably multiple case classes are necessary. Alternatively specify the defaults values and use these in the `YamlProtocol`.

The general idea is to add the default configuration during the deserialization (read) in the `YamlProtocol` files.

The `data_collection` part is optional from the user's point of view so we need to check if it was specified in the `YamlProtocol`. If not specified we add it and then continue down the tree. If it was specified we check if `client_side` was specified in that `YamlProtocol` and so on, until we have specified all.
