### ISSUE TITLE
Add stored knowledge setting

### ISSUE THREAD

**Issue by jeppe-style** [benchflow/benchflow#444]
We also need to add an optional value in the DSL so that the expert user can turn the feature off and force the execution even if a match was found. Agreed to be
```
configuration:
  # OPTIONAL
  settings:
    # OPTIONAL
    enable_stored_knowledge: Boolean # default is true
```
